// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConsumeLaunchPath() {
  return window['go']['main']['App']['ConsumeLaunchPath']();
}

export function DedupeSelected(arg1) {
  return window['go']['main']['App']['DedupeSelected'](arg1);
}

export function KeepSingletonSelected(arg1) {
  return window['go']['main']['App']['KeepSingletonSelected'](arg1);
}

export function ListFolder(arg1) {
  return window['go']['main']['App']['ListFolder'](arg1);
}

export function LoadSession() {
  return window['go']['main']['App']['LoadSession']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function OpenTextFile() {
  return window['go']['main']['App']['OpenTextFile']();
}

export function OpenTextFileByPath(arg1) {
  return window['go']['main']['App']['OpenTextFileByPath'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SaveTextFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFileAs'](arg1, arg2);
}

export function ToInListSelected(arg1) {
  return window['go']['main']['App']['ToInListSelected'](arg1);
}
