// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelChatStream(arg1) {
  return window['go']['main']['App']['CancelChatStream'](arg1);
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConsumeLaunchPath() {
  return window['go']['main']['App']['ConsumeLaunchPath']();
}

export function CreateConversation(arg1, arg2) {
  return window['go']['main']['App']['CreateConversation'](arg1, arg2);
}

export function DedupeSelected(arg1) {
  return window['go']['main']['App']['DedupeSelected'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExtractFromText(arg1, arg2) {
  return window['go']['main']['App']['ExtractFromText'](arg1, arg2);
}

export function FetchAIModels(arg1) {
  return window['go']['main']['App']['FetchAIModels'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function KeepSingletonSelected(arg1) {
  return window['go']['main']['App']['KeepSingletonSelected'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListFolder(arg1) {
  return window['go']['main']['App']['ListFolder'](arg1);
}

export function LoadSession() {
  return window['go']['main']['App']['LoadSession']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function OpenReleasesPage() {
  return window['go']['main']['App']['OpenReleasesPage']();
}

export function OpenTextFile() {
  return window['go']['main']['App']['OpenTextFile']();
}

export function OpenTextFileByPath(arg1) {
  return window['go']['main']['App']['OpenTextFileByPath'](arg1);
}

export function RenameConversation(arg1, arg2) {
  return window['go']['main']['App']['RenameConversation'](arg1, arg2);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SaveTextFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFileAs'](arg1, arg2);
}

export function SelectConversation(arg1) {
  return window['go']['main']['App']['SelectConversation'](arg1);
}

export function SetConversationModel(arg1, arg2) {
  return window['go']['main']['App']['SetConversationModel'](arg1, arg2);
}

export function SetVersion(arg1) {
  return window['go']['main']['App']['SetVersion'](arg1);
}

export function StartChatStream(arg1) {
  return window['go']['main']['App']['StartChatStream'](arg1);
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}

export function ToInListSelected(arg1) {
  return window['go']['main']['App']['ToInListSelected'](arg1);
}
