// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConsumeLaunchPath():Promise<string>;

export function DedupeSelected(arg1:string):Promise<main.ToolResult>;

export function KeepSingletonSelected(arg1:string):Promise<main.ToolResult>;

export function ListFolder(arg1:string):Promise<main.ListFolderResult>;

export function LoadSession():Promise<main.SessionPayload>;

export function Log(arg1:string):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenFolder():Promise<main.OpenFolderResult>;

export function OpenLogDir():Promise<void>;

export function OpenTextFile():Promise<main.OpenFileResult>;

export function OpenTextFileByPath(arg1:string):Promise<main.OpenFileResult>;

export function SaveSession(arg1:main.SessionPayload):Promise<boolean>;

export function SaveTextFile(arg1:string,arg2:string):Promise<main.SaveFileResult>;

export function SaveTextFileAs(arg1:string,arg2:string):Promise<main.SaveFileResult>;

export function ToInListSelected(arg1:string):Promise<main.ToolResult>;
